### ISSUE TITLE
any tutorial for building a third party framework for ue4?

### ISSUE THREAD

**Issue by evehal** [gameDNAstudio/MobileUtils#7]
i built a framework following this tutorial
https://www.youtube.com/watch?v=i7Yq2B00u9g
and put the framework into plugin.
ue4 ios package succeed,but my ipad can not launch the app

here is the log:
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/IOSNativeLib.framework/IOSNativeLib | Referenced from: /var/containers/Bundle/Application/EDB6FA91-60A6-47BD-8664-E74E928F6EFA/IOSPluginTest.app/IOSPluginTest | Reason: image not found
Triggered by Thread:  0

Filtered syslog:
None found

Thread 0 Crashed:
0   dyld                          	0x000000010735af1c __abort_with_payload + 8
1   dyld                          	0x000000010735a6f4 abort_with_payload_wrapper_internal + 100
2   dyld                          	0x000000010735a720 fcntl + 0
3   dyld                          	0x0000000107330498 dyld::fastBindLazySymbol+ 17560 (ImageLoader**, unsigned long) + 0
4   dyld                          	0x0000000107333714 dyld::_main+ 30484 (macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 7376
5   dyld                          	0x000000010732d21c _dyld_start + 68

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016f9d2500   x3: 0x00000000000000b1
    x4: 0x000000016f9d2100   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000d40
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x4f492f7070612e74  x11: 0x546e6967756c5053
   x12: 0x20200a747365546e  x13: 0x203a6e6f73616552  x14: 0x6f6e206567616d69  x15: 0x00646e756f662074
   x16: 0x0000000000000209  x17: 0x0000000000000010  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016f9d2100  x21: 0x00000000000000b1  x22: 0x000000016f9d2500  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x000000010042c000  x26: 0x000000010736e000  x27: 0x000000010736df88
   x28: 0x000000016f9d3b00   fp: 0x000000016f9d20d0   lr: 0x000000010735a6f4
    sp: 0x000000016f9d2090   pc: 0x000000010735af1c cpsr: 0x00000000

Binary Images:
0x10042c000 - 0x104933fff IOSPluginTest arm64  <cd553e75e7113caa9543fc4c88bdc71b> /var/containers/Bundle/Application/EDB6FA91-60A6-47BD-8664-E74E928F6EFA/IOSPluginTest.app/IOSPluginTest
0x10732c000 - 0x10736bfff dyld arm64  <113803ec7f6936e6b06abef57a8755fd> /usr/lib/dyld

EOF

thanks for any help

**Comment by gameDNAstudio** [comment]
Currently we don't have any tutorial but have plans to publish one in the future. Stay tuned! :)
