### ISSUE TITLE
Retrieving Auth Token from Online Subsystem is not working

### ISSUE THREAD

**Issue by CSKazuma** [gameDNAstudio/MobileUtils#9]
It seems like one of your features: the Auth Token can not be acquired. Well GoogleAuthUtil.getToken is deprecated and therefore completly useless. Its recommend the change for Auth.GOOGLE_SIGN_IN. There is a migration guide:
https://developers.google.com/identity/sign-in/android/migration-guide
but this shall be done as an request pull for the unreal engine itself or at least epic shall change it.

**Comment by Taikatou** [comment]
Is this finished?

**Comment by gameDNAstudio** [comment]
Hello,

Yes, you are right. This no longer works but is not related directly to our plugin. This is a problem in deprecated implementation inside UE4. We should wait when it will be fixed or you can use "Sign In With Google" function (which returns needed Id Token and works for Android and iOS as well) from Ultimate Mobile Kit plugin (https://gamednastudio.com/ultimate-mobile-kit/) if you owned it.

Patrick,
gameDNA Ltd

**Comment by CSKazuma** [comment]
> 
> 
> Is this finished?

It mind be possible that already in 4.21 the migration mind be complete and the recommend new Auth.GOOGLE_SIGN_IN method will be fully featured as for the google recommend API lvl 26.
Maybe the Auth Token and the Auth Code will be also exposed to blueprints in the new engine version.

**Comment by gameDNAstudio** [comment]
Hello,

We studied code in 4.21 and nothing has been changed in this case...
